export const PP_questions = {
    'Q1A' : 'I found myself getting upset by quite trivial things.',
    'Q2A' : 'I was aware of dryness of my mouth.',
    'Q3A' : 'I couldn\'t seem to experience any positive feeling at all.',
    'Q4A' : 'I experienced breathing difficulty (eg, excessively rapid breathing, breathlessness in the absence of physical exertion).',
    'Q5A' : 'I just couldn\'t seem to get going.',
    'Q6A' : 'I tended to over-react to situations.',
    'Q7A' : 'I had a feeling of shakiness (eg, legs going to give way).',
    'Q8A' : 'I found it difficult to relax.',
    'Q9A' : 'I found myself in situations that made me so anxious I was most relieved when they ended.',
    'Q10A' : 'I felt that I had nothing to look forward to.',
    'Q11A' : 'I found myself getting upset rather easily.',
    'Q12A' : 'I felt that I was using a lot of nervous energy.',
    'Q13A' : 'I felt sad and depressed.',
    'Q14A' : 'I found myself getting impatient when I was delayed in any way (eg, elevators, traffic lights, being kept waiting).',
    'Q15A' : 'I had a feeling of faintness.',
    'Q16A' : 'I felt that I had lost interest in just about everything.',
    'Q17A' : 'I felt I was not worth much as a person.',
    'Q18A' : 'I felt that I was rather touchy.',
    'Q19A' : 'I perspired noticeably (eg, hands sweaty) in the absence of high temperatures or physical exertion.',
    'Q20A' : 'I felt scared without any good reason.',
    'Q21A' : 'I felt that life was not worthwhile.',
    'Q22A' : 'I found it hard to wind down.',
    'Q23A' : 'I had difficulty in swallowing.',
    'Q24A' : 'I could not seem to get any enjoyment out of the things I did.',
    'Q25A' : 'I was aware of the action of my heart in the absence of physical exertion (eg, sense of heart rate increase, heart missing a beat).',
    'Q26A' : 'I felt down-hearted and blue.',
    'Q27A' : 'I found that I was very irritable.',
    'Q28A' : 'I felt I was close to panic.',
    'Q29A' : 'I found it hard to calm down after something upset me.',
    'Q30A' : 'I feared that I would be \'thrown\' by some trivial but unfamiliar task.',
    'Q31A' : 'I was unable to become enthusiastic about anything.',
    'Q32A' : 'I found it difficult to tolerate interruptions to what I was doing.',
    'Q33A' : 'I was in a state of nervous tension.',
    'Q34A' : 'I felt I was pretty worthless.',
    'Q35A' : 'I was intolerant of anything that kept me from getting on with what I was doing.',
    'Q36A' : 'I felt terrified.',
    'Q37A' : 'I could see nothing in the future to be hopeful about.',
    'Q38A' : 'I felt that life was meaningless.',
    'Q39A' : 'I found myself getting agitated.',
    'Q40A' : 'I was worried about situations in which I might panic and make a fool of myself.',
    'Q41A' : 'I experienced trembling (eg, in the hands).',
    'Q42A' : 'I found it difficult to work up the initiative to do things.',
}

export const to_predict ={
    'TIPI1' : 'Extroverted, enthusiastic.',
    'TIPI2' : 'Critical, quarrelsome.',
    'TIPI3' : 'Dependable, self-disciplined.',
    'TIPI4' : 'Anxious, easily upset.',
    'TIPI5' : 'Open to new experiences, complex',
    'TIPI6' : 'Reserved, quiet',
    'TIPI7' : 'Sympathetic, warm.',
    'TIPI8' : 'Disorganized, careless.',
    'TIPI9' : 'Calm, emotionally stable.',
    'TIPI10' : 'Conventional, uncreative.',
}

export const avg = {
    'TIPI1' : 3.7,
    'TIPI2' : 4.19,
    'TIPI3' : 4.74,
    'TIPI4' : 5.17,
    'TIPI5' : 4.93,
    'TIPI6' : 4.85,
    'TIPI7' : 5.27,
    'TIPI8' : 4.28,
    'TIPI9' : 3.64,
    'TIPI10' : 3.73,
}